In [8]:
import numpy as np
np.__version__

'1.26.4'

In [9]:
a=np.array([[3,4],[5,6]])
a

array([[3, 4],
       [5, 6]])

In [10]:
b=np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

In [11]:
a@b

matrix([[15, 22],
        [23, 34]])

In [12]:
np.dot(a,b)

matrix([[15, 22],
        [23, 34]])

In [13]:
a*b

matrix([[15, 22],
        [23, 34]])

In [14]:
np.multiply(a,b)

matrix([[ 3,  8],
        [15, 24]])

In [15]:
a

array([[3, 4],
       [5, 6]])

In [16]:
a@a

array([[29, 36],
       [45, 56]])

In [17]:
np.dot(a,a)

array([[29, 36],
       [45, 56]])

In [18]:
np.prod(a)

360

In [19]:
a*a

array([[ 9, 16],
       [25, 36]])

In [20]:
np.multiply(a,a)

array([[ 9, 16],
       [25, 36]])

In [21]:
b

matrix([[1, 2],
        [3, 4]])

In [22]:
b@b

matrix([[ 7, 10],
        [15, 22]])

In [23]:
np.dot(b,b
      )

matrix([[ 7, 10],
        [15, 22]])

In [24]:
b*b

matrix([[ 7, 10],
        [15, 22]])

In [25]:
np.multiply(b,b)

matrix([[ 1,  4],
        [ 9, 16]])

In [26]:
np.prod(b)

24

In [27]:
a.data

In [28]:
type(a)

numpy.ndarray

In [29]:
a

array([[3, 4],
       [5, 6]])

In [30]:
b

matrix([[1, 2],
        [3, 4]])

In [31]:
a+1

array([[4, 5],
       [6, 7]])

In [32]:
a*2

array([[ 6,  8],
       [10, 12]])

In [33]:
np.diagonal(a)

array([3, 6])

In [34]:
np.ones_like(a)

array([[1, 1],
       [1, 1]])

In [35]:
a

array([[3, 4],
       [5, 6]])

In [36]:
c=np.ones((4))
c

array([1., 1., 1., 1.])

In [37]:
d=np.array([[5],[5],[5],[5]])
d

array([[5],
       [5],
       [5],
       [5]])

In [38]:
d+c

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [39]:
np.prod(d)

625

In [40]:
np.sum(d)

20

In [41]:
np.cumsum(d)

array([ 5, 10, 15, 20])

In [42]:
np.subtract(d,1)

array([[4],
       [4],
       [4],
       [4]])

In [43]:
d

array([[5],
       [5],
       [5],
       [5]])

In [44]:
np.subtract(d,2)

array([[3],
       [3],
       [3],
       [3]])

In [45]:
d

array([[5],
       [5],
       [5],
       [5]])

In [46]:
np.divide(d,2)

array([[2.5],
       [2.5],
       [2.5],
       [2.5]])

In [47]:
np.divide(d,d)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [48]:
d

array([[5],
       [5],
       [5],
       [5]])

In [49]:
np.floor_divide(d,2)

array([[2],
       [2],
       [2],
       [2]])

In [50]:
np.sqrt(5)

2.23606797749979

In [51]:
np  .nan

nan

In [52]:
np.info

<function numpy.info(object=None, maxwidth=76, output=None, toplevel='numpy')>

In [53]:
np.inf

inf

In [54]:
np.random.uniform(5,10,(1+2,1+2,1+2))

array([[[8.66822625, 8.31044189, 7.86300485],
        [6.86481161, 7.09577283, 7.54248685],
        [6.59981383, 5.33578922, 8.67207   ]],

       [[8.02506763, 5.39870898, 8.10860775],
        [7.73913364, 5.7876454 , 7.84172609],
        [5.57709814, 9.23861411, 7.73440471]],

       [[6.80046188, 6.23273104, 7.0417134 ],
        [7.6171097 , 5.95309031, 7.07760316],
        [8.29673057, 9.64812926, 9.82467527]]])

In [55]:
np.random.normal(5,1)

4.676823955363363

In [56]:
range_number=range(1,10,2)
range_number

range(1, 10, 2)

In [62]:
np.arange(1,10,3)

array([1, 4, 7])

In [66]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [69]:
numbers=np.arange(1,10)

In [70]:
numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
mask=numbers%2==0

In [78]:
mask

array([False,  True, False,  True, False,  True, False,  True, False])

In [79]:
numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
numbers[mask]

array([2, 4, 6, 8])

In [81]:
np.logical_or(numbers>=2,numbers<=8,numbers==3)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [96]:
numbers[(numbers>2 )&(numbers <6)]

array([3, 4, 5])

In [98]:
a

array([[3, 4],
       [5, 6]])

In [99]:
b

matrix([[1, 2],
        [3, 4]])

In [100]:
c

array([1., 1., 1., 1.])

In [101]:
d

array([[5],
       [5],
       [5],
       [5]])

In [102]:
np.unique(d)

array([5])

In [108]:
np.size(a)

4

In [109]:
np.size(b)

4

In [110]:
bb=np.array([[1,2],[3,4]])
bb

array([[1, 2],
       [3, 4]])

In [115]:
np.union1d(a,d)

array([3, 4, 5, 6])

In [120]:
np.intersect1d(a,bb)

array([3, 4])

In [121]:
a

array([[3, 4],
       [5, 6]])

In [122]:
np.sum(a)

18

In [123]:
np.mean(a)

4.5

In [124]:
np.median(a)

4.5

In [125]:
b

matrix([[1, 2],
        [3, 4]])

In [126]:
np.sum(b)

10

In [127]:
np.mean(b)

2.5

In [128]:
bb

array([[1, 2],
       [3, 4]])

In [129]:
aa=np.array([[8,4],[47,10]])
aa

array([[ 8,  4],
       [47, 10]])

In [130]:
np.sum(aa)

69

In [131]:
np.mean(aa)

17.25

In [132]:
np.median(aa)

9.0

In [133]:
np.sort(aa)

array([[ 4,  8],
       [10, 47]])

In [134]:
np.sort_complex(aa)

array([[ 4.+0.j,  8.+0.j],
       [10.+0.j, 47.+0.j]])

In [135]:
np.std(aa)

17.311484627264065

In [136]:
a

array([[3, 4],
       [5, 6]])

In [137]:
np.std(a)

1.118033988749895

In [138]:
np.var(a)

1.25

In [139]:
np.var(aa)

299.6875

In [141]:
pn=np.array([1,2,2]) #polynomial

In [145]:
np.polyval(pn,2)

10

In [146]:
np.polyder(pn)

array([2, 2])

In [147]:
np.polyint(pn)

array([0.33333333, 1.        , 2.        , 0.        ])

In [148]:
np.polyint([2,2])

array([1., 2., 0.])