In [1]:
import numpy as np

In [2]:
import sys

In [3]:
sys.executable

'/home/mohammad-hossein-abedi/Documents/Code/Machine_learning_Puyan_Rajiyan/bin/python'

In [4]:
np.__version__

'1.26.4'

In [5]:
import pandas as pd

In [6]:
pd.__version__

'2.2.2'

In [7]:
rows=pd.Series([1,2,3,4,5,6,7,8,9])
rows

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [8]:
rows=pd.Series(rows.values,index=['row1','row2','row3','row4','row5','row6','row7','row8','row9'])

In [10]:
rows.values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
print (1)

1


In [12]:
rows.values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
rows.index

Index(['row1', 'row2', 'row3', 'row4', 'row5', 'row6', 'row7', 'row8', 'row9'], dtype='object')

In [14]:
rows

row1    1
row2    2
row3    3
row4    4
row5    5
row6    6
row7    7
row8    8
row9    9
dtype: int64

In [15]:
rows.values


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
rows.row9

9

In [18]:
rows['row8']

8

In [22]:
rows[(rows>6) & (rows<9)]

row7    7
row8    8
dtype: int64

In [23]:
rows.rename({'row1':1, 'row2':2, 'row3':3})

1       1
2       2
3       3
row4    4
row5    5
row6    6
row7    7
row8    8
row9    9
dtype: int64

In [24]:
rows

row1    1
row2    2
row3    3
row4    4
row5    5
row6    6
row7    7
row8    8
row9    9
dtype: int64

In [50]:
df=pd.DataFrame([[1,2,3,4],[5,6,7,8],[9,10,11,12]],index=['row1','row2','row3']
               ,columns=['column1','column2','column3','column4'])

In [51]:
df


column1  column2  column3  column4
row1        1        2        3        4
row2        5        6        7        8
row3        9       10       11       12

In [28]:
df.index

Index(['row1', 'row2', 'row3'], dtype='object')

In [29]:
df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
df.mean

<bound method DataFrame.mean of       column1  column2  column3  column4
row1        1        2        3        4
row2        5        6        7        8
row3        9       10       11       12>

In [31]:
df.median

<bound method DataFrame.median of       column1  column2  column3  column4
row1        1        2        3        4
row2        5        6        7        8
row3        9       10       11       12>

In [32]:
np.mean(df)

6.5

In [35]:
np.var(df,axis=1)

row1    1.25
row2    1.25
row3    1.25
dtype: float64

In [58]:
df.loc['row2','column4']

8

In [45]:
df.iloc[2,0]

9

In [52]:
df

column1  column2  column3  column4
row1        1        2        3        4
row2        5        6        7        8
row3        9       10       11       12

In [54]:
df['row4']=[13,14,15]

In [55]:
df

column1  column2  column3  column4  row4
row1        1        2        3        4    13
row2        5        6        7        8    14
row3        9       10       11       12    15

In [61]:
df.reset_index(drop=True,inplace=False)

column1  column2  column3  column4  row4
0        1        2        3        4    13
1        5        6        7        8    14
2        9       10       11       12    15

In [72]:
df.loc[:,'column3':'row4']=0

In [73]:
df

column1  column2  column3  column4  row4
row1        1        2        0        0     0
row2        5        6        0        0     0
row3        9       10        0        0     0

In [77]:
df.rename(columns={'row4':'column5'})

column1  column2  column3  column4  column5
row1        1        2        0        0        0
row2        5        6        0        0        0
row3        9       10        0        0        0

In [78]:
df

column1  column2  column3  column4  row4
row1        1        2        0        0     0
row2        5        6        0        0     0
row3        9       10        0        0     0

In [79]:
df.drop('row4',axis=1,inplace=True)

In [80]:
df

column1  column2  column3  column4
row1        1        2        0        0
row2        5        6        0        0
row3        9       10        0        0

In [81]:
df.replace(0,1)

column1  column2  column3  column4
row1        1        2        1        1
row2        5        6        1        1
row3        9       10        1        1

In [82]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of       column1  column2  column3  column4
row1        1        2        0        0
row2        5        6        0        0
row3        9       10        0        0>

In [83]:
df

column1  column2  column3  column4
row1        1        2        0        0
row2        5        6        0        0
row3        9       10        0        0

In [84]:
df.dropna

<bound method DataFrame.dropna of       column1  column2  column3  column4
row1        1        2        0        0
row2        5        6        0        0
row3        9       10        0        0>

In [85]:
df

column1  column2  column3  column4
row1        1        2        0        0
row2        5        6        0        0
row3        9       10        0        0

In [89]:
df.replace(0,'NaN',inplace=True)

In [90]:
df

column1  column2 column3 column4
row1        1        2     NaN     NaN
row2        5        6     NaN     NaN
row3        9       10     NaN     NaN

In [94]:
df.replace('NaN',0,inplace=True)

/tmp/ipykernel_8313/1758626276.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('NaN',0,inplace=True)


In [98]:
df.replace(0,np.nan,inplace=True)

In [99]:
df

column1  column2  column3  column4
row1        1        2      NaN      NaN
row2        5        6      NaN      NaN
row3        9       10      NaN      NaN

In [135]:
df['column1']=df['column1'].apply(lambda x:'{:.2f}'.format(x))

ValueError: Unknown format code 'f' for object of type 'str'

In [134]:
df

column1  column2  column3  column4
row1    1.00        2      NaN      NaN
row2    5.00        6      NaN      NaN
row3    9.00       10      NaN      NaN

In [136]:
df.size

12

In [137]:
df.shape

(3, 4)

In [138]:
type(df.iloc[1,0])

str

In [139]:
df

column1  column2  column3  column4
row1    1.00        2      NaN      NaN
row2    5.00        6      NaN      NaN
row3    9.00       10      NaN      NaN

In [144]:
df.sort_index(axis=0)

column1  column2  column3  column4
row1    1.00        2      NaN      NaN
row2    5.00        6      NaN      NaN
row3    9.00       10      NaN      NaN

In [158]:
df.drop('column4',axis=1,inplace=True)

In [161]:
df.replace(np.nan,0,inplace=True)

In [162]:
df

column1  column2  column3
row1    1.00        2      0.0
row2    5.00        6      0.0
row3    9.00       10      0.0

In [167]:
df.sort_values(by='column1',ascending=True)

column1  column2  column3
row1    1.00        2      0.0
row2    5.00        6      0.0
row3    9.00       10      0.0

In [168]:
df .head(2) 

column1  column2  column3
row1    1.00        2      0.0
row2    5.00        6      0.0

In [169]:
df   .tail(2)

column1  column2  column3
row2    5.00        6      0.0
row3    9.00       10      0.0

In [170]:
df2=pd.read_csv('smartphones.csv')

In [171]:
df2

Name        OS  Capacity  Ram  Weight    Company  inch
0         Galaxy S10   Android       128    8   163.0    Samsung   6.2
1          Lumia 950  windows         32    3   150.0  Microsoft   5.2
2        Xpreia 1 ll   Android       256    8   181.0       Sony   6.5
3          iphone 7        ios       128    2   138.0      Apple   4.7
4            U Ultra   Android        64    4   170.0        HTC   5.7
5          Galaxy S5   Android        16    2   145.0    Samsung   5.1
6  iphone 11 pro max       ios       256    4   226.0      Apple   6.5
7            Moto G5   Android        16    3   144.5   Motorola   5.0
8             Pixel    Android       128    4   143.0     Google   5.0